# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.19"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "shellcode-template"
include-after = [ "cmake/shellcode.cmake" ]

[template.shellcode]
type = "executable"
add-function = "add_shellcode_executable"

[target.shellcode-template]
type = "shellcode"
sources = [ 
	"src/*.c"
]
